# Generated by Django 3.0.5 on 2020-04-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Cctv',
            },
        ),
        migrations.CreateModel(
            name='CctvLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('appearance_time', models.DateTimeField()),
                ('car_model', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='car.Car', to_field='model')),
                ('cctv_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recognition.Cctv')),
            ],
            options={
                'db_table': 'CctvLog',
            },
        ),
    ]
